name: DS course CI

on:
  pull_request:
    types:
      - opened
      - synchronize
    branches:
      - main

jobs:
  Task-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Run task CI
        if: startsWith(github.event.pull_request.head.ref, 'task')
        run: BRANCH=$(git rev-parse --abbrev-ref HEAD)
          TASK=$(echo "$BRANCH" | cut -d'/' -f1)
          PROG_LANG=$(echo "$BRANCH" | cut -d'/' -f2)
          make run
