name: DS course CI

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run task CI
        if: startsWith(github.event.pull_request.head.ref, 'task')
        run: make run-ci
